name: EasyDuels
version: 1.6.0
description: Simple 1V1 plugin.
author: Enzias
main: fr.enzias.easyduels.EasyDuels
api-version: 1.13
softdepend: [Vault]
commands:
  easyduels:
    description: Main command
    permission: easyduels.duel
    usage: /<command>
permissions:
  easyduels.*:
    description: Gives access to all Easyduels commands.
    default: op
    children:
      easyduels.admin.*: true
      easyduels.duel: true
      easyduels.help: true
      easyduels.queue: true
      easyduels.spectate: true
      easyduels.money: true
      easyduels.myprofile: true
      easyduels.othersprofile: true
  easyduels.admin.*:
    default: false
    children:
      easyduels.admin.set: true
      easyduels.admin.reload: true
      easyduels.admin.help: true
      easyduels.admin.manager: true
      easyduels.admin.rank: true
      easyduels.admin.rankall: true
  easyduels.duel:
    default: true
  easyduels.help:
    default: true
  easyduels.queue:
    default: true
  easyduels.money:
    default: true
  easyduels.spectate:
    default: true
  easyduels.myprofile:
    default: false
