name: EasyDuels
version: 1.5.0
description: Simple 1V1 plugin.
author: Enzias
main: fr.enzias.easyduels.EasyDuels
api-version: 1.13
softdepend: [Vault]
commands:
  easyduels:
    description: Main command
    permission: easyduels.duel
    usage: /<command>
permissions:
  easyduels.*:
    description: Gives access to all Easyduels commands.
    default: op
    children:
      easyduels.admin: true
      easyduels.duel: true
      easyduels.help: true
      easyduels.queue: true
  easyduels.admin:
    description: Gives access to admin command.
    default: false
  easyduels.duel:
    description: Allows you to make duels.
    default: true
  easyduels.help:
    description: Gives access to help command.
    default: true
  easyduels.queue:
    description: Gives access to queue command.
    default: true
  easyduels.money:
    description: Allows you to make duels with money bet.
    default: true
  easyduels.spectate:
    description: Gives access to spectate command.
    default: true
