settings:
  check-for-updates: true
  command-aliases:
    - 'easyduel'
    - 'ed'
    - 'duel'
    - 'duels'
  blocked-commands:
    all: false
    inventory: true
    blacklisted-commands:
      - 'spawn'
      - 'tp'
    whitelisted-commands:
      - 'tell'
      - 'ban'
  queue:
    enable: true
    max-players: 15
    queue-join:
      message-to-player: '&f[&6&lEasy&c&lDuels&f] &aYou joined the queue. Your position: &2%player_position%# &a!'
      title-to-player:
        - '&aYou joined the queue!'
        - '&2(&a%player_position%&2/&a%queue_size%&2)'
      sound-to-player:
        sound-id: 'ENTITY_VILLAGER_YES'
        volume: 1
        pitch: 1
      actionbar-to-player: '&aSuccessfully joined the queue. %queue_size% players in the queue.'
    queue-leave:
      message-to-player: '&f[&6&lEasy&c&lDuels&f] &cYou left the queue. &6%queue_size% players &cin the queue now.'
      title-to-player:
        - '&cYou left the queue!'
        - '&6%queue_size% players in the queue now.'
      sound-to-player:
        sound-id: 'ENTITY_VILLAGER_NO'
        volume: 1
        pitch: 1
      actionbar-to-player: '&cSuccessfully left the queue.'
    queue-update:
      message-to-player: '&f[&6&lEasy&c&lDuels&f] &aYour position in the queue: &2%player_position%&a/&2%queue_size%'
      title-to-player:
        - '&aYour position in the queue:'
        - '&a%player_position%&2/&a%queue_size%'
      sound-to-players:
        sound-id: 'ENTITY_VILLAGER_YES'
        volume: 1
        pitch: 1
      actionbar-to-player: '&aYour position in the queue: &2%player_position%&a/&2%queue_size%'
  money-bet:
    enable: true
    minimum-amount: 5000
    maximum-amount: 100000
  spectate:
    enable: true
    gamemode: 'SPECTATOR'
    after-spectate-gamemode: 'SURVIVAL'
    blocked-commands:
      all: false
      inventory: true
      blacklisted-commands:
        - 'spawn'
        - 'tp'
      whitelisted-commands:
        - 'tell'
        - 'ban'
  timer:
    sync-timer: true
    request:
      expiration: 30
    lobby:
      duration: 10
      prevent-move: true
      actions:
        '10':
          message-to-players: '&6The game starts in 10 seconds!'
          title-to-players:
            - '&aThe Duel is starting!'
            - '&6Be ready!'
          sound-to-players:
            sound-id: 'BLOCK_ANVIL_LAND'
            volume: 1
            pitch: 1
          actionbar-to-players: '&cStarting in &610 &cseconds'
          broadcast: '&aA duel is starting between %player1% and %player2%!'
        '9':
          actionbar-to-players: '&cStarting in &69 &cseconds'
        '8':
          actionbar-to-players: '&cStarting in &68 &cseconds'
        '7':
          actionbar-to-players: '&cStarting in &67 &cseconds'
        '6':
          actionbar-to-players: '&cStarting in &66 &cseconds'
        '5':
          actionbar-to-players: '&cStarting in &65 &cseconds'
        '4':
          actionbar-to-players: '&cStarting in &64 &cseconds'
        '3':
          actionbar-to-players: '&cStarting in &63 &cseconds'
          title-to-players:
            - '&aStarting in'
            - '&c3'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_HARP'
            volume: 1
            pitch: 0
        '2':
          actionbar-to-players: '&cStarting in &62 &cseconds'
          title-to-players:
            - '&aStarting in'
            - '&62'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_HARP'
            volume: 1
            pitch: 0
        '1':
          actionbar-to-players: '&cStarting in &61 &cseconds'
          title-to-players:
            - '&aStarting in'
            - '&c1'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_HARP'
            volume: 1
            pitch: 0
        '0':
          title-to-players:
            - '&cFight'
            - '&6Good luck!'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_HARP'
            volume: 1
            pitch: 1
    fight:
      duration: 300
      gamemode: 'SURVIVAL'
      actions:
        all:
          actionbar-to-players: '&cTime remaining : &6%timer%'
        '60':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &660 seconds remaining!'
          title-to-players:
            - '&660 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '30':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &630 seconds remaining!'
          title-to-players:
            - '&630 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '15':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &615 seconds remaining!'
          title-to-players:
            - '&615 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '10':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &610 seconds remaining!'
          title-to-players:
            - '&610 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '3':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &63 seconds remaining!'
          title-to-players:
            - '&63 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '2':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &62 seconds remaining!'
          title-to-players:
            - '&62 seconds'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
        '1':
          message-to-players: '&f[&6&lEasy&c&lDuels&f] &61 seconds remaining!'
          title-to-players:
            - '&61 second'
            - '&6Remaining'
          sound-to-players:
            sound-id: 'BLOCK_NOTE_BELL'
            volume: 1
            pitch: 1
    end:
      duration: 10
      gamemode: 'SURVIVAL'
      keep-inventory: true
      actions:
        results-message: true
        fake-explosion: true
        firework: true
        teleport:
          winner: 0
          loser: 2
          no-winner: 1
          spectator: 0
        bet-message-to-winner: '&f[&6&lEasy&c&lDuels&f] &aYou won the money bet: &2%amount% coins&a!'
        bet-message-to-loser: '&f[&6&lEasy&c&lDuels&f] &cYou lost the money bet: &6%amount% coins&c!'
        bet-message-no-winner: '&f[&6&lEasy&c&lDuels&f] &6No one won the money bet! You missed: &c%amount% coins&6!'
        title-to-winner:
          - '&aWinner'
          - '&6You won the duel!'
        title-to-loser:
          - '&cLoser'
          - '&6You lost the duel!'
        title-no-winner:
          - '&cDraw!'
          - '&6There is no winner!'
        sound-to-winner:
          sound-id: 'ENTITY_PLAYER_LEVELUP'
          volume: 1
          pitch: 1
        sound-to-loser:
          sound-id: 'ENTITY_WITHER_DEATH'
          volume: 1
          pitch: 1
        sound-no-winner:
          sound-id: 'BLOCK_END_PORTAL_SPAWN'
          volume: 1
          pitch: 1
        actionbar-to-winner: '&aYou won the duel!'
        actionbar-to-loser: '&cYou lost the duel!'
        actionbar-no-winner: '&6There is no winner!'
        reward-commands:
          - 'give %winner% diamond_block 1'
          - 'give %loser% diamond 1'
        broadcast: '&f[&6&lEasy&c&lDuels&f] &c%winner% &6won the duel against &c%loser%&6!'
        broadcast-no-winner: '&f[&6&lEasy&c&lDuels&f] &6No one won in the duel between &c%player1% and &c%player2%&6!'
